const response = {
    candle: [
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '', shadowL: 0, shadowH: 0, open: 0, close: 0 },
        { time: '2021-07-23 10:28:06', shadowL: 90.2, shadowH: 95.3, open: 90.3, close: 94.4 }
    ],
    volume: [

    ]
}

export default response